name: Build images

on: 
  push: 
  workflow_dispatch:

permissions:
    packages: write
    contents: read

jobs:
  build:
    name: Build image
    runs-on: ubuntu-20.04
    env: 
      IMAGE: ghcr.io/${{ github.repository }}
    strategy:
      fail-fast: true
      matrix:
        arch: [ amd64, arm64v8 ]
        type: [ mariadb, postgresql ]
        include:
          - arch: amd64
            platform: linux/amd64
          - arch: arm64v8
            platform: linux/arm64
    steps: 
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/metadata-action@v5
        id: image-metadata
        with: 
          images: ghcr.io/${{ github.repository }}
          tags: type=raw,value=${{ matrix.type }}-${{ matrix.arch }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          platforms: ${{ matrix.platform }}
          tags: ${{ steps.image-metadata.outputs.tags }}
          args: IMAGE_TAG=${{ matrix.type }}

  merge:
    runs-on: ubuntu-20.04
    needs: [ build ]
    strategy:
      fail-fast: true
      matrix:
        type: [ mariadb, postgresql ]
    steps: 
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker buildx imagetools create \
            --tag ${IMAGE}:${{ matrix.type }} ${IMAGE}:${{ matrix.type }}-{amd64,arm64v8}
